[workspace]
members = ["cli", "api"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/silentspike/mainrag"
homepage = "https://github.com/silentspike/mainrag"
authors = ["obtFusi <85476984+obtFusi@users.noreply.github.com>"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"

[profile.dev]
opt-level = 0
